#!/bin/bash
# Generate FSR4 initializer data headers from .bin files (Linux port of BuildFSR4Initializers.bat)
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHADER_DIR="$SCRIPT_DIR/internal/shaders"
OUTPUT_DIR="${1:-$SCRIPT_DIR/internal/permutations/vk}"

mkdir -p "$OUTPUT_DIR"

MODELS=(
    fsr4_model_v07_fp8_no_scale_native
    fsr4_model_v07_fp8_no_scale_quality
    fsr4_model_v07_fp8_no_scale_balanced
    fsr4_model_v07_fp8_no_scale_performance
    fsr4_model_v07_fp8_no_scale_drs
    fsr4_model_v07_fp8_no_scale_ultraperf
)

for model in "${MODELS[@]}"; do
    bin_file="$SHADER_DIR/$model/initializers.bin"
    if [ ! -f "$bin_file" ]; then
        echo "SKIP: $bin_file not found"
        continue
    fi

    file_size=$(stat -c%s "$bin_file" 2>/dev/null || stat -f%z "$bin_file" 2>/dev/null)
    echo "  Generating: $model ($file_size bytes)"

    # Generate .cpp with byte array
    {
        echo "// auto-generated by generate_initializers.sh"
        echo "extern const unsigned char g_${model}_initializers_data[] = {"
        xxd -i < "$bin_file" | sed 's/^/  /'
        echo "};"
    } > "$OUTPUT_DIR/${model}.cpp"

    # Generate .h with size constant
    {
        echo "// auto-generated by generate_initializers.sh"
        echo "#pragma once"
        echo "extern const unsigned char g_${model}_initializers_data[];"
        echo "static const size_t g_${model}_initializers_size = ${file_size};"
    } > "$OUTPUT_DIR/${model}.h"

    echo "    -> ${model}.h + ${model}.cpp"
done

echo "Done. Output: $OUTPUT_DIR"
